const { BrevoClient } = require('@getbrevo/brevo');
const PDFDocument = require('pdfkit');

/**
 * Generates the PDF in memory.
 * Returns a Promise that resolves to a Buffer.
 */
function generatePDFBuffer(session) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];
      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        resolve(Buffer.concat(buffers));
      });
      doc.on('error', reject);

      // --- Draw PDF ---
      doc.fontSize(10).text('---------------------------------------------------------------------------------');
      doc.fontSize(16).fillColor('#2563EB').text('INTERVIU AI', { align: 'left' });
      doc.fillColor('black');
      doc.fontSize(14).text('INTERVIEW PERFORMANCE REPORT', { align: 'left' }).moveDown(0.5);
      doc.fontSize(10).text('---------------------------------------------------------------------------------').moveDown();

      doc.fontSize(12).text('Candidate Interview').moveDown(0.5);
      doc.fontSize(10).text(`Domain: ${session.configuration.domain}`);
      doc.text(`Interview Type: ${session.configuration.type}`);
      doc.text(`Difficulty: ${session.configuration.difficulty}`);
      if (session.configuration.company) {
        doc.text(`Company: ${session.configuration.company === 'GENERIC' ? 'Generic Interview' : session.configuration.company}`);
      }
      if (session.configuration.role) {
        doc.text(`Role: ${session.configuration.role}`);
      }
      doc.text(`Date: ${new Date(session.createdAt).toLocaleDateString()}`).moveDown();

      doc.fontSize(14).text('OVERALL SCORE');
      doc.fontSize(12).fillColor('#2563EB').text(`${session.overallScore ?? 'N/A'} / 100`).moveDown();
      doc.fillColor('black');

      doc.fontSize(12).text('FEEDBACK SUMMARY');
      doc.fontSize(10).text(session.feedbackSummary || 'Not available.').moveDown();

      if (session.strengths && session.strengths.length > 0) {
        doc.fontSize(12).fillColor('#16A34A').text('STRENGTHS');
        doc.fontSize(10).fillColor('black');
        session.strengths.forEach(s => doc.text(`• ${s}`));
        doc.moveDown();
      }

      if (session.weaknesses && session.weaknesses.length > 0) {
        doc.fontSize(12).fillColor('#DC2626').text('WEAKNESSES');
        doc.fontSize(10).fillColor('black');
        session.weaknesses.forEach(w => doc.text(`• ${w}`));
        doc.moveDown();
      }

      if (session.recommendations && session.recommendations.length > 0) {
        doc.fontSize(12).fillColor('#2563EB').text('RECOMMENDATIONS');
        doc.fontSize(10).fillColor('black');
        session.recommendations.forEach(r => doc.text(`• ${r}`));
        doc.moveDown();
      }

      doc.addPage();
      doc.fontSize(14).text('QUESTION PERFORMANCE').moveDown();

      session.questions.forEach((q, idx) => {
        doc.fontSize(12).text(`Question ${idx + 1}`);
        doc.fontSize(10).text(`Q: ${q.text}`);
        doc.text(`Answer: ${q.userAnswer || 'No answer provided'}`);
        if (q.evaluation) {
          doc.fillColor('#2563EB').text(`Score: ${q.evaluation.score}/100`);
          doc.fillColor('black').text(`Feedback: ${q.evaluation.feedback}`);
        } else {
          doc.fillColor('#6B7280').text('Evaluation: Not available.');
        }
        doc.fillColor('black').moveDown();
      });

      doc.fontSize(10).fillColor('#6B7280').text('---------------------------------------------------------------------------------');
      doc.text('Generated by Interviu AI');

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

/**
 * Generates PDF and sends via Brevo
 */
const sendInterviewReport = async (user, session) => {
  if (!process.env.BREVO_API_KEY || !process.env.BREVO_FROM_EMAIL) {
    console.warn('[EMAIL] BREVO_API_KEY or BREVO_FROM_EMAIL not configured. Skipping email.');
    return;
  }
  
  if (!user || !user.email) {
    console.warn('[EMAIL] User email not available. Skipping email.');
    return;
  }

  const apiInstance = new BrevoClient({
    apiKey: process.env.BREVO_API_KEY
  });

  try {
    const pdfBuffer = await generatePDFBuffer(session);
    
    const sendSmtpEmail = {
      subject: "Your Interview Report is Ready",
      htmlContent: `
      <html>
        <body>
          <h2>Your Interview Report is Ready</h2>
          <p>Hi ${user.firstName || 'Candidate'},</p>
          <p>Your interview for <strong>${session.configuration.domain}</strong> has been successfully evaluated.</p>
          <p><strong>Overall Score:</strong> ${session.overallScore ?? 'N/A'}/100</p>
          <p>We've attached your detailed performance report as a PDF to this email.</p>
          <p>You can also review your full performance analytics anytime from your dashboard.</p>
          <br/>
          <p>Keep up the great work!</p>
          <p>The Interviu AI Team</p>
        </body>
      </html>
    `,
      sender: {
        name: process.env.BREVO_FROM_NAME || "Interview AI",
        email: process.env.BREVO_FROM_EMAIL
      },
      to: [
        { email: user.email, name: user.firstName ? `${user.firstName} ${user.lastName || ''}` : "Student" }
      ],
      attachment: [
        {
          name: `interview-report-${session._id}.pdf`,
          content: pdfBuffer.toString('base64')
        }
      ]
    };

    const data = await apiInstance.transactionalEmails.sendTransacEmail(sendSmtpEmail);
    console.log('[EMAIL] Successfully sent report email to', user.email, 'MessageId:', data.messageId);
  } catch (error) {
    console.error('[EMAIL] Failed to send interview report email:', error);
    throw error;
  }
};

module.exports = {
  sendInterviewReport
};
